version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo "Starting build"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 149920196491.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=149920196491.dkr.ecr.us-east-2.amazonaws.com/pablo-node-cv
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Building application"
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    debug: true
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"pablo-cv","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json 
      - echo "Build complete"

artifacts:
    files: imagedefinitions.json
      
